// import type { Metadata } from "next";
// import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      // className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <div className="flex flex-col min-h-screen">
          <header className="bg-blue-500 p-4 flex gap-4">
            <Link href="/blog">blogs</Link>
            <Link href="/register">register</Link>
            <Link href="/login">login</Link>
            <Link href="/forgot-password">forgot password</Link>
          </header>
          <main className="flex-grow">
            {children}
          </main>
          <footer className="bg-gray-500 p-4">
            <p>footer</p>
          </footer>
        </div>
      </body>
    </html>
  );
}